services:
  postgres:
    image: postgres:16
    container_name: student_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studentdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d studentdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  student_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: student_api
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=studentdb;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
